### PR TITLE
Add SDL demo 2D game application.

### PR DESCRIPTION
**Pull request by marcin-hajkowski-epam**

### CODE REVIEW

**Comment by bcatrysse** [comment]
We need to add appropriate License headers to the code. Is this code coming from existing licensed code, then we need to respect that license. Or did you make this yourself from scratch (in such case we can add apachev2 license and epam copyrights

**Comment by ZbyszekK** [comment]
Font attached to application (SEASRN.ttf) is "freeware", however on strange licence https://www.onlinewebfonts.com/download/d752c6b519f93f913528983fc33711a3 You might include the font in PS or PDF file, but the licence does not state explicitly if you can use the font in the game.  Shouldn't we rather use some already integrated in yocto font?
https://layers.openembedded.org/layerindex/branch/dunfell/recipes/?q=ttf  ?

**Comment by ZbyszekK** [comment]
Are those two files with game graphics "mapTile.png", "player.png" your own art?

**Comment by marcin-hajkowski-epam** [comment]
for mapTile.png I use content from:

https://grimfaith.itch.io/platformer-tileset

for player animation I work on my own graphic and I will replace existing one, I will also use one of the Yocto fonts to avoid any license inaccuracies.

**Review by ZbyszekK — APPROVED** [review]

**Pull request merged**
